# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_rows_bcf <- function(prior_tree_table_temp, grow_node) {
    .Call(`_bcfbma_add_rows_bcf`, prior_tree_table_temp, grow_node)
}

addcol_bcf <- function(prior_tree_matrix_temp, grow_node, ld_obs, rd_obs) {
    .Call(`_bcfbma_addcol_bcf`, prior_tree_matrix_temp, grow_node, ld_obs, rd_obs)
}

set_daughter_to_end_tree_bcf <- function(grow_node, prior_tree_table_temp, left_daughter) {
    .Call(`_bcfbma_set_daughter_to_end_tree_bcf`, grow_node, prior_tree_table_temp, left_daughter)
}

set_daughter_to_end_mat_bcf <- function(d, prior_tree_matrix_temp, left_daughter, ld_obs, rd_obs) {
    .Call(`_bcfbma_set_daughter_to_end_mat_bcf`, d, prior_tree_matrix_temp, left_daughter, ld_obs, rd_obs)
}

remove_zero_bcf <- function(nodes_at_depth) {
    .Call(`_bcfbma_remove_zero_bcf`, nodes_at_depth)
}

order_intvec_bcf <- function(x) {
    .Call(`_bcfbma_order_intvec_bcf`, x)
}

get_gnp_bcf <- function(nodes_at_depth, grow_node) {
    .Call(`_bcfbma_get_gnp_bcf`, nodes_at_depth, grow_node)
}

find_term_nodes_bcf <- function(tree_table) {
    .Call(`_bcfbma_find_term_nodes_bcf`, tree_table)
}

find_term_obs_bcf <- function(tree_matrix_temp, terminal_node) {
    .Call(`_bcfbma_find_term_obs_bcf`, tree_matrix_temp, terminal_node)
}

likelihood_function_mu_bcf <- function(y_temp, treetable_temp, obs_to_nodes_temp, a, mu, nu, lambda) {
    .Call(`_bcfbma_likelihood_function_mu_bcf`, y_temp, treetable_temp, obs_to_nodes_temp, a, mu, nu, lambda)
}

likelihood_function_bcf <- function(y_temp, treetable_temp, obs_to_nodes_temp, a, mu, nu, lambda) {
    .Call(`_bcfbma_likelihood_function_bcf`, y_temp, treetable_temp, obs_to_nodes_temp, a, mu, nu, lambda)
}

find_internal_nodes_bcf <- function(treetable) {
    .Call(`_bcfbma_find_internal_nodes_bcf`, treetable)
}

find_prev_nonterm_bcf <- function(find_nonterm, prev) {
    .Call(`_bcfbma_find_prev_nonterm_bcf`, find_nonterm, prev)
}

find_nodes_to_update_bcf <- function(all_ld, left_daughter) {
    .Call(`_bcfbma_find_nodes_to_update_bcf`, all_ld, left_daughter)
}

set_tree_to_middle_bcf <- function(node_to_update, prior_tree_table_temp, grow_node, left_daughter) {
    .Call(`_bcfbma_set_tree_to_middle_bcf`, node_to_update, prior_tree_table_temp, grow_node, left_daughter)
}

update_grow_obs_bcf <- function(prior_tree_matrix_temp, grow_node, left_daughter, d, ld_obs, rd_obs) {
    .Call(`_bcfbma_update_grow_obs_bcf`, prior_tree_matrix_temp, grow_node, left_daughter, d, ld_obs, rd_obs)
}

find_obs_to_update_grow_bcf <- function(prior_tree_matrix_temp, left_daughter, d, ld_obs, rd_obs) {
    .Call(`_bcfbma_find_obs_to_update_grow_bcf`, prior_tree_matrix_temp, left_daughter, d, ld_obs, rd_obs)
}

get_daughter_obs_bcf <- function(xmat, obs_to_update, split_var, split_point) {
    .Call(`_bcfbma_get_daughter_obs_bcf`, xmat, obs_to_update, split_var, split_point)
}

find_term_cols_bcf <- function(tree_matrix_temp, terminal_node) {
    .Call(`_bcfbma_find_term_cols_bcf`, tree_matrix_temp, terminal_node)
}

get_grow_obs_bcf <- function(xmat, grow_obs, split_var) {
    .Call(`_bcfbma_get_grow_obs_bcf`, xmat, grow_obs, split_var)
}

get_grow_obs_in_z_bcf <- function(z_ar, grow_obs) {
    .Call(`_bcfbma_get_grow_obs_in_z_bcf`, z_ar, grow_obs)
}

grow_tree_bcf <- function(xmat, y, prior_tree_matrix, grow_node, prior_tree_table, splitvar, splitpoint, terminal_nodes, grow_obs, d, get_min, data_curr_node) {
    .Call(`_bcfbma_grow_tree_bcf`, xmat, y, prior_tree_matrix, grow_node, prior_tree_table, splitvar, splitpoint, terminal_nodes, grow_obs, d, get_min, data_curr_node)
}

set_daughter_bcf <- function(left_daughter, right_daughter, ld_obs, rd_obs, tree_matrix_temp, term_cols) {
    .Call(`_bcfbma_set_daughter_bcf`, left_daughter, right_daughter, ld_obs, rd_obs, tree_matrix_temp, term_cols)
}

order__bcf <- function(x) {
    .Call(`_bcfbma_order__bcf`, x)
}

orderforOW__bcf <- function(x) {
    .Call(`_bcfbma_orderforOW__bcf`, x)
}

get_tree_prior_bcf <- function(tree_table, tree_matrix, alpha, beta) {
    .Call(`_bcfbma_get_tree_prior_bcf`, tree_table, tree_matrix, alpha, beta)
}

start_tree_bcf <- function(start_mean, start_sd) {
    .Call(`_bcfbma_start_tree_bcf`, start_mean, start_sd)
}

start_matrix_bcf <- function(n) {
    .Call(`_bcfbma_start_matrix_bcf`, n)
}

evaluate_model_occams_window_bcf <- function(tree_lik, lowest_BIC, c, tree_list, tree_mat_list, tree_parent) {
    .Call(`_bcfbma_evaluate_model_occams_window_bcf`, tree_lik, lowest_BIC, c, tree_list, tree_mat_list, tree_parent)
}

get_testdata_term_obs_bcf <- function(test_data, tree_data, term_node_means) {
    .Call(`_bcfbma_get_testdata_term_obs_bcf`, test_data, tree_data, term_node_means)
}

resize_bcf <- function(x, n) {
    .Call(`_bcfbma_resize_bcf`, x, n)
}

resize_bigger_bcf <- function(x, n) {
    .Call(`_bcfbma_resize_bigger_bcf`, x, n)
}

J_bcf <- function(treetable_temp, obs_to_nodes_temp, tree_term_nodes) {
    .Call(`_bcfbma_J_bcf`, treetable_temp, obs_to_nodes_temp, tree_term_nodes)
}

mu_vector_bcf <- function(sum_treetable, n) {
    .Call(`_bcfbma_mu_vector_bcf`, sum_treetable, n)
}

W_bcf <- function(sum_treetable, sum_obs_to_nodes, n) {
    .Call(`_bcfbma_W_bcf`, sum_treetable, sum_obs_to_nodes, n)
}

W_tauround1_bcf <- function(treetable, obs_to_nodes, n) {
    .Call(`_bcfbma_W_tauround1_bcf`, treetable, obs_to_nodes, n)
}

sumtree_likelihood_function_bcf_bcf <- function(y_temp, sum_treetable_mu, sum_treetable_tau, sum_obs_to_nodes_mu, sum_obs_to_nodes_tau, n, a_mu, a_tau, nu, lambda, z) {
    .Call(`_bcfbma_sumtree_likelihood_function_bcf_bcf`, y_temp, sum_treetable_mu, sum_treetable_tau, sum_obs_to_nodes_mu, sum_obs_to_nodes_tau, n, a_mu, a_tau, nu, lambda, z)
}

sumtree_likelihood_tau_round1_bcf <- function(y_temp, treetable_tau, obs_to_nodes_tau, n, a_mu, a_tau, nu, lambda, z) {
    .Call(`_bcfbma_sumtree_likelihood_tau_round1_bcf`, y_temp, treetable_tau, obs_to_nodes_tau, n, a_mu, a_tau, nu, lambda, z)
}

get_best_split_mu_bcf <- function(resids, data, treetable, tree_mat, a, mu, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha, beta, maxOWsize) {
    .Call(`_bcfbma_get_best_split_mu_bcf`, resids, data, treetable, tree_mat, a, mu, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha, beta, maxOWsize)
}

get_best_split_bcf <- function(resids, data, treetable, tree_mat, a, mu, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha, beta, maxOWsize, first_round) {
    .Call(`_bcfbma_get_best_split_bcf`, resids, data, treetable, tree_mat, a, mu, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha, beta, maxOWsize, first_round)
}

get_best_split_tau_bcf <- function(resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, z) {
    .Call(`_bcfbma_get_best_split_tau_bcf`, resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, z)
}

get_best_split_tau_round1_bcf <- function(resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_mat_mu, y_scaled, parent2, i, z) {
    .Call(`_bcfbma_get_best_split_tau_round1_bcf`, resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_mat_mu, y_scaled, parent2, i, z)
}

get_best_split_sum_tau_bcf <- function(resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, parent2, i, z) {
    .Call(`_bcfbma_get_best_split_sum_tau_bcf`, resids, x_moderate_a, tree_table_tau, tree_mat_tau, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, parent2, i, z)
}

get_best_split_sum_mu_bcf <- function(resids, x_control_a, tree_table_mu, tree_mat_mu, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, parent2, i, z) {
    .Call(`_bcfbma_get_best_split_sum_mu_bcf`, resids, x_control_a, tree_table_mu, tree_mat_mu, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, lowest_BIC, parent, cp_mat, alpha_mu, beta_mu, alpha_tau, beta_tau, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, parent2, i, z)
}

update_mean_var_bcf <- function(tree_table, tree_matrix, resids, a) {
    .Call(`_bcfbma_update_mean_var_bcf`, tree_table, tree_matrix, resids, a)
}

update_predictions_bcf <- function(tree_table, tree_matrix, new_mean, n) {
    .Call(`_bcfbma_update_predictions_bcf`, tree_table, tree_matrix, new_mean, n)
}

subsetter_bcf <- function(a, b) {
    .Call(`_bcfbma_subsetter_bcf`, a, b)
}

order_inc__bcf <- function(x) {
    .Call(`_bcfbma_order_inc__bcf`, x)
}

min_which2_bcf <- function(array, n, minout, whichout) {
    .Call(`_bcfbma_min_which2_bcf`, array, n, minout, whichout)
}

mll_meanvar2_bcf <- function(x, x2, n) {
    .Call(`_bcfbma_mll_meanvar2_bcf`, x, x2, n)
}

PELT_meanvar_norm2_bcf <- function(resp, pen) {
    .Call(`_bcfbma_PELT_meanvar_norm2_bcf`, resp, pen)
}

SS_bcf <- function(x, y, split) {
    .Call(`_bcfbma_SS_bcf`, x, y, split)
}

gridCP_bcf <- function(x, y, gridSize = 10L) {
    .Call(`_bcfbma_gridCP_bcf`, x, y, gridSize)
}

make_gridpoint_cpmat_mu_bcf <- function(data, resp, gridsize, num_cp) {
    .Call(`_bcfbma_make_gridpoint_cpmat_mu_bcf`, data, resp, gridsize, num_cp)
}

make_gridpoint_cpmat_tau_bcf <- function(data, resp, gridsize, num_cp, z) {
    .Call(`_bcfbma_make_gridpoint_cpmat_tau_bcf`, data, resp, gridsize, num_cp, z)
}

make_pelt_cpmat_mu_bcf <- function(data, resp, pen, num_cp) {
    .Call(`_bcfbma_make_pelt_cpmat_mu_bcf`, data, resp, pen, num_cp)
}

make_pelt_cpmat_tau_bcf <- function(data, resp, pen, num_cp, z) {
    .Call(`_bcfbma_make_pelt_cpmat_tau_bcf`, data, resp, pen, num_cp, z)
}

get_best_trees_mu_bcf <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, zero_split) {
    .Call(`_bcfbma_get_best_trees_mu_bcf`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, zero_split)
}

get_best_trees_mu_bcf_2 <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, zero_split, no_more_mu_trees) {
    .Call(`_bcfbma_get_best_trees_mu_bcf_2`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, zero_split, no_more_mu_trees)
}

get_best_trees_sum_mu_bcf <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_mu, zero_split) {
    .Call(`_bcfbma_get_best_trees_sum_mu_bcf`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_mu, zero_split)
}

get_best_trees_sum_mu_bcf_2 <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_mu, zero_split, no_more_mu_trees) {
    .Call(`_bcfbma_get_best_trees_sum_mu_bcf_2`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_mu, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_mu, zero_split, no_more_mu_trees)
}

get_best_trees_tau_bcf <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_tau, zero_split, no_more_tau_trees) {
    .Call(`_bcfbma_get_best_trees_tau_bcf`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_tau, zero_split, no_more_tau_trees)
}

get_best_trees_sum_tau_round1_bcf <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_mat_mu, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split) {
    .Call(`_bcfbma_get_best_trees_sum_tau_round1_bcf`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_mat_mu, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split)
}

get_best_trees_sum_tau_bcf <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split) {
    .Call(`_bcfbma_get_best_trees_sum_tau_bcf`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split)
}

get_best_trees_sum_tau_bcf_2 <- function(x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split, no_more_tau_trees) {
    .Call(`_bcfbma_get_best_trees_sum_tau_bcf_2`, x_control_a, x_moderate_a, z, resids, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, tree_table_mu, tree_mat_mu, tree_table_tau, tree_mat_tau, lowest_BIC, parent, resids_cp_mat_tau, err_list, x_control_test, x_moderate_test, test_z, alpha_mu, alpha_tau, beta_mu, beta_tau, is_test_data, pen_mu, num_cp_mu, pen_tau, num_cp_tau, split_rule_node, gridpoint, maxOWsize, prev_sum_trees_mu, prev_sum_trees_tau, prev_sum_trees_mat_mu, prev_sum_trees_mat_tau, y_scaled, num_splits_mu, num_splits_tau, gridsize_tau, zero_split, no_more_tau_trees)
}

scale_response_bcf <- function(a, b, c, d, y) {
    .Call(`_bcfbma_scale_response_bcf`, a, b, c, d, y)
}

get_original_bcf <- function(low, high, sp_low, sp_high, sum_preds) {
    .Call(`_bcfbma_get_original_bcf`, low, high, sp_low, sp_high, sum_preds)
}

BCF_BMA_sumLikelihood <- function(data, y, z, pihat, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, pen_mu, pen_tau, num_cp_mu, num_cp_tau, test_data, test_z, test_pihat, ntree_control, ntree_moderate, alpha_mu, alpha_tau, beta_mu, beta_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, gridsize_tau, include_pi2, zero_split, only_max_num_trees) {
    .Call(`_bcfbma_BCF_BMA_sumLikelihood`, data, y, z, pihat, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, pen_mu, pen_tau, num_cp_mu, num_cp_tau, test_data, test_z, test_pihat, ntree_control, ntree_moderate, alpha_mu, alpha_tau, beta_mu, beta_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, gridsize_tau, include_pi2, zero_split, only_max_num_trees)
}

fuse_intvecs <- function(a, b) {
    .Call(`_bcfbma_fuse_intvecs`, a, b)
}

fuse_numvecs <- function(a, b) {
    .Call(`_bcfbma_fuse_numvecs`, a, b)
}

fuse_lists <- function(a, b) {
    .Call(`_bcfbma_fuse_lists`, a, b)
}

fuse_listsof_intvecs <- function(a, b) {
    .Call(`_bcfbma_fuse_listsof_intvecs`, a, b)
}

mmult1 <- function(a, b) {
    .Call(`_bcfbma_mmult1`, a, b)
}

BCF_BMA_sumLikelihood_add_mu_or_tau <- function(data, y, z, pihat, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, pen_mu, pen_tau, num_cp_mu, num_cp_tau, test_data, test_z, test_pihat, ntree_control, ntree_moderate, alpha_mu, alpha_tau, beta_mu, beta_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, gridsize_tau, include_pi2, zero_split, only_max_num_trees, separate_tree_numbers) {
    .Call(`_bcfbma_BCF_BMA_sumLikelihood_add_mu_or_tau`, data, y, z, pihat, a_mu, a_tau, mu_mu, mu_tau, nu, lambda, c, sigma_mu_mu, sigma_mu_tau, pen_mu, pen_tau, num_cp_mu, num_cp_tau, test_data, test_z, test_pihat, ntree_control, ntree_moderate, alpha_mu, alpha_tau, beta_mu, beta_tau, split_rule_node, gridpoint, maxOWsize, num_splits_mu, num_splits_tau, gridsize_mu, gridsize_tau, include_pi2, zero_split, only_max_num_trees, separate_tree_numbers)
}

find_term_nodes_gs <- function(tree_table) {
    .Call(`_bcfbma_find_term_nodes_gs`, tree_table)
}

find_term_obs_gs <- function(tree_matrix_temp, terminal_node) {
    .Call(`_bcfbma_find_term_obs_gs`, tree_matrix_temp, terminal_node)
}

calc_rowsums <- function(predictions) {
    .Call(`_bcfbma_calc_rowsums`, predictions)
}

calculate_resids <- function(predictions, response) {
    .Call(`_bcfbma_calculate_resids`, predictions, response)
}

update_Gibbs_mean_var <- function(tree_table, resids, a, sigma, mu_mu, terminal_nodes, term_obs_tree) {
    .Call(`_bcfbma_update_Gibbs_mean_var`, tree_table, resids, a, sigma, mu_mu, terminal_nodes, term_obs_tree)
}

update_sigma <- function(a1, b, resids, n) {
    .Call(`_bcfbma_update_sigma`, a1, b, resids, n)
}

find_node_means <- function(sum_tree, term_nodes) {
    .Call(`_bcfbma_find_node_means`, sum_tree, term_nodes)
}

get_tree_info <- function(overall_sum_trees, overall_sum_mat, num_obs) {
    .Call(`_bcfbma_get_tree_info`, overall_sum_trees, overall_sum_mat, num_obs)
}

get_tree_info_tau <- function(overall_sum_trees, overall_sum_mat, num_obs, z) {
    .Call(`_bcfbma_get_tree_info_tau`, overall_sum_trees, overall_sum_mat, num_obs, z)
}

remove_curr_col <- function(predy, i) {
    .Call(`_bcfbma_remove_curr_col`, predy, i)
}

get_new_mean <- function(terminal_nodes, new_mean_var) {
    .Call(`_bcfbma_get_new_mean`, terminal_nodes, new_mean_var)
}

update_predictions_gs <- function(tree_table, new_mean, new_var, n, terminal_nodes, term_obs_tree) {
    .Call(`_bcfbma_update_predictions_gs`, tree_table, new_mean, new_var, n, terminal_nodes, term_obs_tree)
}

scale_response_gs <- function(a, b, c, d, y) {
    .Call(`_bcfbma_scale_response_gs`, a, b, c, d, y)
}

get_original_gs <- function(low, high, sp_low, sp_high, sum_preds) {
    .Call(`_bcfbma_get_original_gs`, low, high, sp_low, sp_high, sum_preds)
}

find_internal_nodes_gs <- function(treetable) {
    .Call(`_bcfbma_find_internal_nodes_gs`, treetable)
}

get_tree_info_test_data <- function(test_data, tree_data) {
    .Call(`_bcfbma_get_tree_info_test_data`, test_data, tree_data)
}

get_tree_info_test_data_tau <- function(test_data, tree_data, z_test) {
    .Call(`_bcfbma_get_tree_info_test_data_tau`, test_data, tree_data, z_test)
}

get_tree_info_testdata_overall <- function(overall_sum_trees, num_obs, test_data) {
    .Call(`_bcfbma_get_tree_info_testdata_overall`, overall_sum_trees, num_obs, test_data)
}

get_tree_info_testdata_overall_tau <- function(overall_sum_trees, num_obs, test_data, z_test) {
    .Call(`_bcfbma_get_tree_info_testdata_overall_tau`, overall_sum_trees, num_obs, test_data, z_test)
}

#' @title Obtain draws from gibbs sampler
#' @export
gibbs_sampler <- function(overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z, test_data, test_pihat, z_test, include_pi2, num_propscores, num_test_obs) {
    .Call(`_bcfbma_gibbs_sampler`, overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z, test_data, test_pihat, z_test, include_pi2, num_propscores, num_test_obs)
}

gibbs_sampler2 <- function(overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z) {
    .Call(`_bcfbma_gibbs_sampler2`, overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z)
}

#' @title Obtain draws from gibbs sampler
#' @export
gibbs_sampler_no_update <- function(overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z, test_data, test_pihat, z_test, include_pi2, num_propscores, num_test_obs) {
    .Call(`_bcfbma_gibbs_sampler_no_update`, overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z, test_data, test_pihat, z_test, include_pi2, num_propscores, num_test_obs)
}

gibbs_sampler_no_update2 <- function(overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z) {
    .Call(`_bcfbma_gibbs_sampler_no_update2`, overall_sum_trees_mu, overall_sum_trees_tau, overall_sum_mat_mu, overall_sum_mat_tau, y, BIC_weights, num_iter, burnin, num_obs, a_mu, a_tau, sigma, mu_mu_mu, mu_mu_tau, nu, lambda, resids_mu, resids_tau, z)
}

